### ISSUE TITLE
CTs in resource discovery response

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#101]
Section 6 includes the resource discovery response examples. In there we see 
>   RES: 2.05 Content 
> </est>; rt="ace.est", /
> </est/crts>;rt="ace.est.crts";ct=281, 
> </est/sen>;rt="ace.est.sen";ct="281 286", 
> </est/sren>;rt="ace.est.sren";ct="281 286", 
> </est/att>;rt="ace.est.att";ct=285, 
> </est/skg>;rt="ace.est.skg";ct="280 286 62"

Let's take /est/sen for example. The request has ct=286. The response has ct=281. Are we supposed to include both ct=281 286 in the resource discovery or just 281? It was not clear from rfc6690 and draft-ietf-core-resource-directory. 

@petervanderstok can you confirm if the request ct should be returned in the resource discovery?

**Comment by mcr** [comment]
Panos K. <notifications@github.com> wrote:
    > Let's take /est/sen for example. The request has ct=286. The response has
    > ct=281. Are we supposed to include both ct=281 286 in the resource
    > discovery
    > or just 281? It was not clear from rfc6690 and
    > draft-ietf-core-resource-directory.

I think just what the response is.
But, I never thought about it.

**Comment by petervanderstok** [comment]
HI,

This is written in 7252, section 7.2.1

The Content-Format code "ct" attribute provides a
hint about the Content-Formats this resource returns. Note that this
is only a hint.

So the ct of the request needs not be included.

I will ask on the CoRE ML.

Peter
Panos K. schreef op 2019-01-16 22:49:

> Section 6 includes the resource discovery response examples. In there we see
> 
>> RES: 2.05 Content
>> ; rt="ace.est", /
>> </est/crts>;rt="ace.est.crts";ct=281,
>> </est/sen>;rt="ace.est.sen";ct="281 286",
>> </est/sren>;rt="ace.est.sren";ct="281 286",
>> </est/att>;rt="ace.est.att";ct=285,
>> </est/skg>;rt="ace.est.skg";ct="280 286 62"
> 
> Let's take /est/sen for example. The request has ct=286. The response has ct=281. Are we supposed to include both ct=281 286 in the resource discovery or just 281? It was not clear from rfc6690 and draft-ietf-core-resource-directory. 
> 
> @petervanderstok [1] can you confirm if the request ct should be returned in the resource discovery? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/petervanderstok
[2] https://github.com/SanKumar2015/EST-coaps/issues/101
[3]

**Comment by petervanderstok** [comment]
Defore changing the text, I should like to wait for any reaction on CoRE ML.

**Comment by petervanderstok** [comment]
Indeed, ct is for content-format returned. Will change text

**Comment by csosto-pk** [comment]
Fixed in commit f57499.
