### ISSUE TITLE
Plain DER instead of PKCS#7 (Esko WGLC review 1/23/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#102]
My main comment on this draft is based on recent experience with an embedded implementation. In the draft, the content format "application/pkcs7-mime;smime-type=certs-only" is used to transport a single certificate back to the client. However, in the embedded implementation crypto library there is no support for parsing this format, but there is support for parsing X.509v3 (application/pkix-cert). See e.g. https://tls.mbed.org/api/group__x509__module.html for an embedded API that can parse CSR and certs, but not PKCS#7.

Therefore the X.509 format seems better to use; also given that 
1) the signing of data that the PKCS#7 S/MIME envelope provides is useless because the DTLS session is already end-to-end protected and the certificate is already signed; and 
2) RFC 7030 requires that only one certificate, the  generated one, is carried in the /simple(re)enroll response so that a container format for multiple certificates is not really needed here.

So to reduce code size for embedded implementations it would be very beneficial if the EST Server would support an additional content format:
application/pkix-cert  (see RFC 5280)

The client can request this format using the CoAP Accept Option; by default if no Accept Option given the EST server would return application/pkcs7-mime;smime-type=certs-only.
What do you think about this addition? I believe that adding this would make the EST-over-Coaps protocol an ideal fit to common embedded SW stacks.

**Comment by csosto-pk** [comment]
The application/pkix-cert is defined in https://tools.ietf.org/html/rfc2585 and registered with IANA in https://www.iana.org/assignments/media-types/application/pkix-cert. 

Esko's equest is to be able to respond to /crt and /sen and /sren with plain DER (instead of PKCS#7). The same could go in the /skg response in the section that includes the cert. 

It seems reasonable to ask for in case PKCS#7 is not supported.  To add it in the draft we would need one more allocation in https://www.iana.org/assignments/core-parameters/core-parameters.xhtml

**Comment by csosto-pk** [comment]
From Michael R. 

> I think that this is a reasonable thing to do.
> The client can easily say what it wants and I think the two formats are relatively easy to swap.

The option for the client to signal is Accept (option 17) (RFC7252)

**Comment by csosto-pk** [comment]
> > I think that this is a reasonable thing to do.
> > The client can easily say what it wants and I think the two formats are relatively easy to swap.

The option for the client to signal is Accept (option 17) (RFC7252)

> > What about if we went further, and went to:
> > Concise Identities
> > draft-birkholz-core-coid-01

I think adding draft-birkholz-core-coid is troublesome as it is not even a WG item. We might as well add support for draft-raza-ace-cbor-certificates. I think neither are mature, supported or standardized anywhere and they should be added.

**Comment by petervanderstok** [comment]
I don't think that we should add dependencies on work in progress
drafts, given the earlier attempts at being timely with this draft.

We can add the format suggested by Esko as optional.

Peter
Panos K. schreef op 2019-01-24 05:56:

> I think that this is a reasonable thing to do.
> The client can easily say what it wants and I think the two formats are relatively easy to swap.

The option for the client to signal is Accept (option 17) (RFC7252)

>> What about if we went further, and went to:
>> Concise Identities
>> draft-birkholz-core-coid-01

I think adding draft-birkholz-core-coid is troublesome as it is not even
a WG item. We might as well add support for
draft-raza-ace-cbor-certificates. I think neither are mature, supported
or standardized anywhere and they should be added. 

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [1], or mute the thread
[2]. 

Links:
------
[1]
https://github.com/SanKumar2015/EST-coaps/issues/102#issuecomment-457066954
[2]

**Comment by csosto-pk** [comment]
Addressed in commit# 92a1b65. 

Added TBD287 in section 10.1. And 
> Content format TBD287 can be used in place of 281 when only one certificate is returned in a /crts, /sen, /sren or /skg response. The client is expected to use an COAP Accept Option in the request to ask for an application/pkix-cert certificate. If an Accept Option is not included in the client request the server SHOULD return content format 281 by default.

And in the appendix 
> The certificate responses included in the examples contain content format 281 (application/pkcs7). If the client had requested content format TBD287 (application/pkix-cert) with an Accept Option, the server would respond a signle DER binary certificate.

**Comment by csosto-pk** [comment]
We still need to add an Accept Option in all the example requests.

**Comment by petervanderstok** [comment]
Accept option explained for /est/skg.
(accept 281) option added for enroll example, with explanation that it is not necessary given that 281 is default.

**Comment by csosto-pk** [comment]
Explained TBD287 Content-Format in place of 281 for certs in stead of PKCS#7 containers.
Also added Accept option in the examples to portray the content-format the client is asking.
