### ISSUE TITLE
Content-Format in the request (Jim's WGLC review 1/28/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#105]
> Section A.2 - I am unclear about the Content-Format note in this example.

> > REQ:
> > GET coaps://[2001:db8::2:1]:61616/est/att
> > (Content-Format: 285)

> If you are asking for a specific content then the correct option would be Accept.  If you are indicating the content type of the response then you should probably put a header line in to that effect.

> In the virtual CoAP WG meeting last week we went through in some explicit detail that both Content-Format and Max-Age have no meaning when appearing on a request and therefore should not be there.

**Comment by petervanderstok** [comment]
the
 RET:
2.05 Content 
is added. (285 refers to the returned payload.

**Comment by csosto-pk** [comment]
One more comment on Jim's point 
> In the virtual CoAP WG meeting last week we went through in some explicit detail that both Content-Format and Max-Age have no meaning when appearing on a request and therefore should not be there.

Just for reference reasons, in EST-coaps the request has a format. It could be an enrollment which means PKCS#10 format. A cacerts request does not need a format because it has no payload. So, some requests in EST-coaps have a content format with a meaning.
