### ISSUE TITLE
.well-known (by Michael)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#106]
> This implies that a server is not required to support /.well-known/est We are not clear about this.  I would prefer that the server ALWAYS supports the well-known names, such that the client can skip doing resource discovery if it thinks that the extra bytes in the URL matter less than additional round trip to do discovery.

**Comment by petervanderstok** [comment]
Te following text is inserted for discovery:

The server MUST be preconfigured with the default
	  /.well-known/est server root resource and port 5684. Resource discovery is necessary when the IP address of the server is unknown to the client. Resource
	  discovery SHOULD be employed when non-default URIs (like /est or
	  /est/ArbitraryLabel) or ports are supported by the server or when the
	  client is unaware of what EST-coaps resources are available by the server.</t>

**Comment by csosto-pk** [comment]
Fixed with commit 7a92d17
