### ISSUE TITLE
Server-side keygen discovery ct values

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#107]
> </est/skg>;rt="ace.est.skg";ct="62 284 281 TBD287"
is wrong. It is missing 280

Should it be 
> ct="62 280 284 281 TBD287"

Or 
></est/skg>;rt="ace.est.skg";ct="280 284 281 TBD287"

I think the second option because 62 is not practically a response content format. It is just the composite response format. 

I think we should either make something like 62_280_281 or 62_280_287 or 62_284_281 or 62_284_287 for all the possible combinations of key and cert formats in the response. Or we should just use "280 284 281 TBD287"

**Comment by petervanderstok** [comment]
Hi Paos,

62 is the content-format number of the valid media-type
application/mutipart-core
that is returned by skg (straight reasoning)
We may eventually add 280, 284, 281 and TBD287 for convenience. (sorry
about the 280, I forgot)

I will add the 280.

Peter
Panos K. schreef op 2019-01-29 14:49:

>> </est/skg>;rt="ace.est.skg";ct="62 284 281 TBD287"
>> is wrong. It is missing 280
> 
> Should it be
> 
>> ct="62 280 284 281 TBD287"
> 
> Or
> 
>> </est/skg>;rt="ace.est.skg";ct="280 284 281 TBD287"
> 
> I think the second option because 62 is not practically a response content format. It is just the composite response format. 
> 
> I think we should either make something like 62_280_281 or 62_280_287 or 62_284_281 or 62_284_287 for all the possible combinations of key and cert formats in the response. Or we should just use "280 284 281 TBD287" 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/SanKumar2015/EST-coaps/issues/107
[2]

**Comment by petervanderstok** [comment]
done
