### ISSUE TITLE
challengePassword: datnietdeert

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#108]
We need a 256-bit (32 characters or 64 hex characters) random value in the challenge password in the CSR in A.2 and C2.

**Comment by petervanderstok** [comment]
Can't do; sorry, openssl requires less than 20 characters

**Comment by petervanderstok** [comment]
changed openssl limit, was forced to create password as character string, and then xml2rfc broke down on the value of challengepassword. Alhough value correct in hex dump, value in unpars wat set to 0x------
