### ISSUE TITLE
Typo: "snd discussed in"

### ISSUE THREAD

**Issue by EskoDijk** [SanKumar2015/EST-coaps#109]
in Section profile7925:
snd discussed in 
-> and discussed in

**Comment by petervanderstok** [comment]
done

Peter
Esko Dijk schreef op 2019-01-30 11:00:

> in Section profile7925:
> snd discussed in
> -> and discussed in 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/SanKumar2015/EST-coaps/issues/109
[2]
