### ISSUE TITLE
Specify which form of "authentication" in 5.1

### ISSUE THREAD

**Issue by EskoDijk** [SanKumar2015/EST-coaps#110]
Section 5.1:

While [RFC7030] permits a number of these functions to be used without
  authentication, this specification requires authentication
  for all functions.

-> It is not indicated here what type of authentication; suggestion is to say "client authentication".

**Comment by petervanderstok** [comment]
suggestion inserted,

peter
Esko Dijk schreef op 2019-01-30 11:05:

> Section 5.1: 
> 
> While [RFC7030] permits a number of these functions to be used without
> authentication, this specification requires authentication
> for all functions. 
> 
> -> It is not indicated here what type of authentication; suggestion is to say "client authentication". 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/SanKumar2015/EST-coaps/issues/110
[2]
