### ISSUE TITLE
Multiple spellings Content-Format / Content Format / content format

### ISSUE THREAD

**Issue by EskoDijk** [SanKumar2015/EST-coaps#118]
In text where a specific content-format is referred, e.g. "content format 281", the spelling differs. Suggest to use one preferred spelling for it.

E.g. use "Content-Format" when referring to the Option, and use "content-format" when referring to the conceptual content-format not the Option. Sometimes it is hard to get it right; I can say "content-format 281" (when talking about that value) or "Content-Format 281" (when talking about an Option with that value).

**Comment by petervanderstok** [comment]
changed them all to Content-Format.
It is really confusing to make the suggested difference.
