### ISSUE TITLE
Long URIs MAY be supported (Klaus WGLC review 2/12/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#124]
In the draft we say 
> Clients and servers MUST support the short resource URIs. The corresponding longer URIs from [RFC7030] MAY be supported." 

Klaus asked 

> Does this provide any benefit or is it just to annoy implementers? Like, we can have short paths, we can have long paths, we cannot decide, so let's have ALL OF THEM!

**Comment by csosto-pk** [comment]
This is a valid point. @petervanderstok I am not sure we added that the "long URIs MAY be supported". Not sure we need that.

**Comment by petervanderstok** [comment]
removed long URIs MAY...
Panos K. schreef op 2019-02-14 22:23:

> This is a valid point. @petervanderstok [1] I am not sure we added that the "long URIs MAY be supported". Not sure we need that. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/petervanderstok
[2]
https://github.com/SanKumar2015/EST-coaps/issues/124#issuecomment-463802836
[3]

**Comment by csosto-pk** [comment]
Removed.
