### ISSUE TITLE
Resource discovery lines MAY (Klaus WGLC review 2/12/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#125]
> The first line of the discovery response above MUST be included. The five consecutive lines after the first MAY be included.

Klaus asked 
> When would I include what?

**Comment by csosto-pk** [comment]
I rephrased the text to say  

>  The first four lines of the discovery response above MUST be returned
>  if the server supports resource discovery.  The last two lines MAY be
>  included if the server supports server discovery and the
>  corresponding EST messages.  The Content-Formats in the response allow
>  the client to request for one that is supported by the server.

**Comment by petervanderstok** [comment]
rephrased that the last two lines are included when the functions are
supported
Panos K. schreef op 2019-02-14 20:39:

> I rephrased the text to say
> 
>> The first four lines of the discovery response above MUST be returned
>> if the server supports resource discovery. The last two lines MAY be
>> included if the server supports server discovery and the
>> corresponding EST messages. The Content-Formats in the response allow
>> the client to request for one that is supported by the server.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/SanKumar2015/EST-coaps/issues/125#issuecomment-463763552
[2]
