### ISSUE TITLE
ace.est (Klaus WGLC review 2/12/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#126]
Klaus asked 

> I understand that EST defines the operations on the resources labeled with annotated with "ace.est.crts", "ace.est.sen", etc. but I don't understand what I can do with a resource that is annotated with "ace.est".

Also he asked about the IANA section 10.2. Resource Type registry that says 
> This EST resource is used to query and return the supported EST resources of a CoAP server.

if 
> there is any specification for how to query and return the supported EST resources?

**Comment by csosto-pk** [comment]
That is a good point. 

@petervanderstok Why did we need "ace.est"?

**Comment by comsats** [comment]
Hi Panos,

Here is a reply I get from one of RISE SICS implementers (Joel). I included him in CC.  If the question was asked for different context, we are missing something then. Do you have a different interpretation?


I don't understand what he thinks is unclear with the current last-version text:


 "In the context of CoAP, the presence and location of (path to) the
   management data are discovered by sending a GET request to "/.well-
   known/core" including a resource type (RT) parameter with the value
   "ace.est" [RFC6690].  Upon success, the return payload will contain
   the root resource of the EST resources."

- I interpret the statement+following example such that "ace.est" only serves as the root resource, with the only purpose to act as the resource type label you use to get info on the paths to the "real" resources, ace.est.crts/ace.est.sen/ace.est.sren and so on.


/Shahid


On 14 Feb 2019, at 22:22, Panos K. <notifications@github.com<mailto:notifications@github.com>> wrote:


That is a good point.

@petervanderstok<https://github.com/petervanderstok> Why did we need "ace.est"?

**Comment by csosto-pk** [comment]
> I don't understand what he thinks is unclear with the current last-version text: "In the context of CoAP, the presence and location of (path to) the management data are discovered by sending a GET request to "/.well- known/core" including a resource type (RT) parameter with the value "ace.est" [RFC6690]. Upon success, the return payload will contain the root resource of the EST resources." 

I think Klaus is asking if we really need the 
> </est>; rt="ace.est", 
in the response payload.

**Comment by petervanderstok** [comment]
explained for the container.
Panos K. schreef op 2019-02-14 22:22:

> That is a good point. 
> 
> @petervanderstok [1] Why did we need "ace.est"? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/petervanderstok
[2]
https://github.com/SanKumar2015/EST-coaps/issues/126#issuecomment-463802322
[3]

**Comment by csosto-pk** [comment]
> explained for the container.

Sorry, 
> This resource is a container of the est resources

does not say why we are returning in the discovery response 
> /<coap://[2001:db8:3::123]:61617/est>;rt="ace.est",

We need more text to explain why we are returning it or at least a reference that we can use as an example where a similar thing is done.

**Comment by csosto-pk** [comment]
Some implementers will make use of the 
> </est>; rt="ace.est",
in the payload. That way he will know that by adding /crts, /sen, /sren to the URI he can send the EST-coaps requests he expects. He doesn't need to parse all the subsequent 
> </est/crts>;rt="ace.est.crts";ct="281 TBD287",
> </est/sen>;rt="ace.est.sen";ct="281 TBD287",
> </est/sren>;rt="ace.est.sren";ct="281 TBD287",

Sent email to Klaus to explain the situation and ask for confirmation. 

If he agrees, we would need to make a slight text change to say only the first line may be returned.

**Comment by csosto-pk** [comment]
Waiting to see if Klaus insists not seeing the root resource ace.est in the response. If he does, I will remove it and leave the client just parse the first </est/crts> to find the root resource.

**Comment by csosto-pk** [comment]
Consensus to remove redundancy of returning ace.est root resource. 
Sorry @mcr . Hopefully you can use only the first line for </est/crts> and extract the crt to get the root resource.

**Comment by csosto-pk** [comment]
Removed redundancy of returning ace.est root resource.

**Comment by mcr** [comment]
Panos K. <notifications@github.com> wrote:
    > Consensus to remove redundancy of returning ace.est root resource.
    > Sorry @mcr . Hopefully you can use only the first line for </est/crts> and
    > extract the crt to get the root resource.

okay, going with consensus.
One can not extract the root resource that way, because actually each
end point could be at different places.  One has to read them all and use the
resource indicated.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [
