### ISSUE TITLE
ct="62 280 284 281 TBD287" (Klaus WGLC review 2/12/2019) 

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#127]
Klaus asked 

> The return of the content types allows the client to choose the most appropriate one." -- Does the example actually match what a server returns? E.g., does ct="62 280 284 281 TBD287" mean that a server actually returns a TBD287 representation or would it always be a 62 (multipart) representation that happens to contain a TBD287 representation?

**Comment by csosto-pk** [comment]
I am not sure we need to return only 62. 

RFC5272 says 
>   The Content-Format code "ct" attribute provides a
>   hint about the Content-Formats this resource returns.  Note that this
>   is only a hint, and it does not override the Content-Format Option of
>   a CoAP response obtained by actually requesting the representation of
>   the resource. [...] The Content-Format code
>   attribute MAY include a space-separated sequence of Content-Format
>   codes, indicating that multiple content-formats are available. 

So ct="62 280 284 281 TBD287" could hint to the client that all the following formats are supported for the multipart server-side keygen.

**Comment by csosto-pk** [comment]
Peter remove them in commit  6d12b50. 

I think we still can keep them there. RFC5272 says 
>   The Content-Format code "ct" attribute provides a
>   hint about the Content-Formats this resource returns.  Note that this
>   is only a hint, and it does not override the Content-Format Option of
>   a CoAP response obtained by actually requesting the representation of
>   the resource. [...] The Content-Format code
>   attribute MAY include a space-separated sequence of Content-Format
>   codes, indicating that multiple content-formats are available. 

So ct="62 280 284 281 TBD287" could hint to the client that all the following formats are supported for the multipart server-side keygen. 

We need to clarify that with Klaus et al.

**Comment by mcr** [comment]
If we resolved the CT issue by allocating 4 CT for the 2x2 combinations, then we would list those for CT here instead of 62 + contents.

**Comment by csosto-pk** [comment]
62 is compulsory. The others are put in as hints if they are supported. 

If we end up defining four new multipart content-format combinations then these will go in the ct="...".

**Comment by csosto-pk** [comment]
According to mailing list discussions, this value can only be 62... 
Need to fix.

**Comment by csosto-pk** [comment]
Fixed. Only kept "ct=62" in the resource discovery response.
