### ISSUE TITLE
Resource discovery href and anchor (Jim WGLC review 2/16/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#136]
Jim made sume comments about the href 

>  The query in section 5.1 to a resource directory is not correct.  It would not go to /.well-known/core but to /rd-lookup (or what ever name is used by the RD).   If this is not intended to be an RD query, then the sentence about it above can be omitted.  

And also 
> Please remove the "anchor" target attribute from the response from the RD.  I believe that this is no longer required and it is just adding noise without adding value.  If this is intended to be from well known then it is sufficient to have the anchor but not to  have the authority section in the href.  
> \</est\>;rt="ace.est";anchor="coaps://2001:db8::123]:61617"

We need to confirm that Jim is OK with the updated text. Also we need to remove the reference to I-D.ietf-core-resource-directory if it is not necessary.

**Comment by csosto-pk** [comment]
Proposed text 

> Discoverable port numbers can be returned in the payload An example response payload for non default CoAPS server port 61617 follows below. Linefeeds were included only for readability.
>
>  REQ: GET /.well-known/core?rt=ace.est*
>  RES: 2.05 Content
> <coap://[2001:db8:3::123]:61617/est>;rt="ace.est",
> <coap://[2001:db8:3::123]:61617/est/crts>;rt="ace.est.crts"; ct="281 TBD287",
> <coap://[2001:db8:3::123]:61617/est/sen>;rt="ace.est.sen";ct="281 TBD287",
> <coap://[2001:db8:3::123]:61617/est/sren>;rt="ace.est.sren";ct="281 TBD287", 
> <coap://[2001:db8:3::123]:61617/est/att>;rt="ace.est.att";ct="285",
> <coap://[2001:db8:3::123]:61617/est/skg>;rt="ace.est.skg";ct="62 280 284 281 TBD287"

Waiting for confirmation from Jim.

**Comment by csosto-pk** [comment]
Jim was OK with the following change 

>  REQ: GET /.well-known/core?rt=ace.est*
>  RES: 2.05 Content
> <coaps://[2001:db8:3::123]:61617/est>;rt="ace.est",
> <coaps://[2001:db8:3::123]:61617/est/crts>;rt="ace.est.crts"; ct="281 TBD287",
> <coaps://[2001:db8:3::123]:61617/est/sen>;rt="ace.est.sen";ct="281 TBD287",
> <coaps://[2001:db8:3::123]:61617/est/sren>;rt="ace.est.sren";ct="281 TBD287", 
> <coaps://[2001:db8:3::123]:61617/est/att>;rt="ace.est.att";ct="285",
> <coaps://[2001:db8:3::123]:61617/est/skg>;rt="ace.est.skg";ct="62 280 284 281 TBD287"

**Comment by petervanderstok** [comment]
still some small mistakes.

forgot <..> for href
skg is just 62 in my opinion as long as multipart-core has not been
changed. 
Panos K. schreef op 2019-02-18 19:33:

> Jim was OK with the following change
> 
>> REQ: GET /.well-known/core?rt=ace.est*
>> RES: 2.05 Content
>> <coaps://[2001:db8:3::123]:61617/est>;rt="ace.est",
>> <coaps://[2001:db8:3::123]:61617/est/crts>;rt="ace.est.crts"; ct="281 TBD287",
>> <coaps://[2001:db8:3::123]:61617/est/sen>;rt="ace.est.sen";ct="281 TBD287",
>> <coaps://[2001:db8:3::123]:61617/est/sren;rt="ace.est.sren";ct="281 TBD287",
>> <coaps://[2001:db8:3::123]:61617/est/att>;rt="ace.est.att";ct="285",
>> <coaps://[2001:db8:3::123]:61617/est/skg>;rt="ace.est.skg";ct="62"
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/SanKumar2015/EST-coaps/issues/136#issuecomment-464837701
[2]

**Comment by csosto-pk** [comment]
> still some small mistakes. forgot <..> for href 

Not sure what you mean by “forgot <..> for href”

> skg is just 62 in my opinion as long as multipart-core has not been changed. 

Check out https://github.com/SanKumar2015/EST-coaps/issues/127 
We can make the change to just “62” after we converge with Klaus

**Comment by petervanderstok** [comment]
something funny with my e-mail because now they, "<>", are there.

peter
Panos K. schreef op 2019-02-19 15:30:

>> still some small mistakes. forgot <..> for href
> 
> Not sure what you mean by "forgot <..> for href"
> 
>> skg is just 62 in my opinion as long as multipart-core has not been changed.
> 
> Check out #127 [1]
> We can make the change to just "62" after we converge with Klaus 
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/SanKumar2015/EST-coaps/issues/127
[2]
https://github.com/SanKumar2015/EST-coaps/issues/136#issuecomment-465150559
[3]

**Comment by csosto-pk** [comment]
Actual text now is 

>   <coaps://[2001:db8:3::123]:61617/est/crts>;rt="ace.est.crts";
>                 ct="281 TBD287",
>   <coaps://[2001:db8:3::123]:61617/est/sen>;rt="ace.est.sen";
>                 ct="281 TBD287",
>   <coaps://[2001:db8:3::123]:61617/est/sren>;rt="ace.est.sren";
>                 ct="281 TBD287",
>   <coaps://[2001:db8:3::123]:61617/est/att>;rt="ace.est.att";
>                 ct="285",
>   <coaps://[2001:db8:3::123]:61617/est/skg>;rt="ace.est.skg";
>                 ct=62
>   <coaps://[2001:db8:3::123]:61617/est/skc>;rt="ace.est.skc";
                 ct=62
