### ISSUE TITLE
Consistent COAP request examples (Klaus WGLC review 2/27/2019) 

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#143]
Klaus pointed out that in A.2 we use 
> POST [2001:db8::2:1]:61616/est/sen 

which is different that A.1 were we say 
> GET coaps://est-coaps.example.org:9085/est/crts
> (Accept:  281)

 It might be good to make this consistent.

**Comment by csosto-pk** [comment]
Replaced all uses of IPv4 or IPv6 addresses to example.com.

**Comment by petervanderstok** [comment]
I am not happy with example.com everywhere. In principle coap is meant for small devices knowing the IP address. Actually earlier comments suggested that both IPv4 and Ipv6 addresses should be used. Suggest to go back to original text.

**Comment by csosto-pk** [comment]
Addressed in commits 82f3bfd and later in 33d098c. 
Closing.
