### ISSUE TITLE
add details about trust relationship between Proxy and Certificate Authority

### ISSUE THREAD

**Issue by mcr** [SanKumar2015/EST-coaps#43]
<pre>
    > @Michael can you look at section 6, see if you agree and create text as
    > suggested by EDnotes in section 6
    > Panos will probably happy to collaborate here

</pre>

**Comment by csosto-pk** [comment]
I updated the Security Considerations subsection that talks about the Registrar. Comments and updates welcome.

**Comment by cisco-sro** [comment]
This probably should be closed as it was addressed.
