### ISSUE TITLE
Comment about discovery ports by Esko

### ISSUE THREAD

**Issue by cisco-sro** [SanKumar2015/EST-coaps#76]
Ok, discovery can happen on port 5684 - in general a CoAP server MAY support discovery on 5684 and MUST support it on 5683 if discovery is offered.
For our purposes, ace-coap-est could require that an EST server MUST offer discovery on port 5684. And we avoid any long-URI issues in the return payload.

**Comment by mcr** [comment]
cisco-sro <notifications@github.com> wrote:
    > Ok, discovery can happen on port 5684 - in general a CoAP server MAY
    > support discovery on 5684 and MUST support it on 5683 if discovery is
    > offered.

Can my server simply not answer port 5683?

**Comment by mcr** [comment]
peter van der stok <notifications@github.com> wrote:
    > Why?

Because running two ports (and a second server), one of which has no purpose
other than discoverying the second one, seems like a waste of code space,
and an opportunity for attack.  Also, the client system needs to have coap
code when it does not need it.

    > A coap server is expected to support discovery on /.well-known/core.

sure, but we only care about coaps.
The client knows it's coaps.

**Comment by petervanderstok** [comment]
added some text on default port numbers for coap and coaps

**Comment by cisco-sro** [comment]
Peter, 

Text says 

> Port numbers, not returned in the example, are assumed to be the default numbers 5683 and 5684 for coap and coaps respectively (sections 12.6 and 12.7 of [RFC7252].

Why 5683? This whole thing is over DTLS and port 5684, right?

**Comment by cisco-sro** [comment]
The consensus was that discovery will be over COAP port 5683. When the client connects to the COAPs resources it will be by default connect on COAPS port 5684 unless specified in the port. 

> Port numbers, not returned in the example, are assumed to be the default numbers 5683 and 5684 for coap and coaps respectively (sections 12.6 and 12.7 of [RFC7252].  Discoverable port numbers MAY be returned in the <href> of the payload.

**Comment by mcr** [comment]
cisco-sro <notifications@github.com> wrote:
    > The consensus was that discovery will be over COAP port 5683.

I don't think we reached consensus.
Topic for WG meeting, I think.

**Comment by cisco-sro** [comment]
From Michael 

> So, in the constrained join situation, who runs the discovery server? Is it on the join proxy?  Does the join proxy do the discovery? 
> Remember that the pledge is only going to have 5684 open on the proxy.

**Comment by petervanderstok** [comment]
clarified discovery section, by reordering text, and by stating that discovery is not needed when client is pre-configured with /.well-known/est URI and port number 5684

**Comment by csosto-pk** [comment]
Looking at the test, I am assuming this is closed, unless someone else thinks differently.
