### ISSUE TITLE
Add text about Expired Certs

### ISSUE THREAD

**Issue by cisco-sro** [SanKumar2015/EST-coaps#79]
Add something in the Security Considerations section about expired IDevID or STAR certs. 

This came from the expired certs auth discussion in LAMPS. There was a mention about the server using CRL info for some time while the cert is expired. Need to pay attention to that.

**Comment by csosto-pk** [comment]
Added 
> IDevID's are expected to have a very long life, as long as the device, and sometimes could expire. In such ocassions the server MAY want to authenticate a client certificate against its trust store although the certificate is expired. 

And in the Security Considerations section 
> In cases where the IDevID used to authenticate the client is expired the server MAY still authenticate the client because IDevIDs are expected to live as long as the device itself. In such occasions, checking the certificate revocation status or authorizing the client using another method is important for the server to ensure that the client is to be trusted.

**Comment by csosto-pk** [comment]
Short-lived certs could also apply here. STAR certs (see ACME WG) could also expire, but revocation checks might not apply here because STAR certs serve the purpose of no revocation checking. Thus there would need to be a distinction between 802.1AR certs and STAR certs in this case.
