### ISSUE TITLE
Response code nits by Oliver (Siemens)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#83]
Appendix A.3 about /sen and /sren appears to have an error and should probably be changed as follows
> After verification of the CSR by the server, a 2.05 Content response with the issued certificate will be returned to the client 
Should become 
> After verification of the CSR by the server, a 2.01 Created response with the issued certificate will be returned to the client

Also 
> The current text seems to be in conflict with itself (later it says: “RET: (Content-Format: 281)(token =0x45) 2.01 Created”) and RFC 7252 (“2.05 Content This Response Code is like HTTP 200 "OK" but only used in response to GET requests.”)

We need to make sure the example use 2.01 and 2.05 according to section 5.1 of the draft that says 
> Every time the HTTP response code 200 is
>  specified in [RFC7030] in response to a GET request, in EST-coaps the
>  equivalent CoAP response code 2.05 or 2.03 MUST be used.  Similarly,
>  2.01, 2.02 or 2.04 MUST be used in response to POST EST requests.
>  Response code HTTP 202 has no equivalent in CoAP.  Section 5.5
>   specifies how EST requests over CoAP handle delayed messages.

Also, in section 5.4 instead of starting with HTTP response codes and then differentiating according HTTP verbs, start with HTTP verbs and then differentiate according HTTP response codes in the text
>	For GET requests with HTTP response code 200 specified by [RFC7030]: the CoAP response code 2.05 or 2.03 MUST be used in EST-coaps
>	For POST requests with HTTP response code 200 specified by [RFC7030]: the CoAP response code 2.01, 2.02 or 2.04 MUST be used in EST-coaps

**Comment by petervanderstok** [comment]
Hi Panos,

will you change the text?

Peter
Panos K. schreef op 2018-10-25 06:00:

> Appendix A.3 about /sen and /sren appears to have an error and should probably be changed as follows
> 
>> After verification of the CSR by the server, a 2.05 Content response with the issued certificate will be returned to the client
>> Should become
>> After verification of the CSR by the server, a 2.01 Created response with the issued certificate will be returned to the client
> 
> Also
> 
>> The current text seems to be in conflict with itself (later it says: "RET: (Content-Format: 281)(token =0x45) 2.01 Created") and RFC 7252 ("2.05 Content This Response Code is like HTTP 200 "OK" but only used in response to GET requests.")
> 
> We need to make sure the example use 2.01 and 2.05 according to section 5.1 of the draft that says
> 
>> Every time the HTTP response code 200 is
>> specified in [RFC7030] in response to a GET request, in EST-coaps the
>> equivalent CoAP response code 2.05 or 2.03 MUST be used. Similarly,
>> 2.01, 2.02 or 2.04 MUST be used in response to POST EST requests.
>> Response code HTTP 202 has no equivalent in CoAP. Section 5.5
>> specifies how EST requests over CoAP handle delayed messages.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/SanKumar2015/EST-coaps/issues/83
[2]

**Comment by csosto-pk** [comment]
> Hi Panos,
> will you change the text?
> Peter

Hi Peter, 
Sure, I can do that. We have some other issues to address too, so no need to submit a new iteration very soon. We can make all the changes we can first.

**Comment by csosto-pk** [comment]
Fixed in commit https://github.com/SanKumar2015/EST-coaps/commit/b08a3886186aeaa6c19569f15f819e5be9f5e874 
Closing this one.
