### ISSUE TITLE
implicit explicit DB and request pipelining

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#85]
EST mandates that when a cacerts is issue the explicit TA is updated. 
By allowing request pipeling in EST-coaps that could mean that the TA does not take effect and the client is using the implicit TA while issuing new requests. We need to put text in the draft to state that this MAY be allowed for contrained environments for performance reasons, but it is RECOMMENDED to update the TA after a cacerts and if that means tearing down the connection it should take place. We need to add language for the MAY and to explain the situation.

**Comment by mcr** [comment]
Panos K. <notifications@github.com> wrote:
    > EST mandates that when a cacerts is issue the explicit TA is updated.

    > By allowing request pipeling in EST-coaps that could mean that the TA
    > does not take effect and the client is using the implicit TA while
    > issuing new requests.

It seems like it's not the requests and responses that we need to order, but
rather the checking of the trust anchors.

    > We need to put text in the draft to state that
    > this MAY be allowed for contrained environments for performance
    > reasons, but it is RECOMMENDED to update the TA after a cacerts and if
    > that means tearing down the connection it should take place. We need to
    > add language for the MAY and to explain the situation.

I don't understand how changing the list of cacerts could change the
ClientCertificate that was used.  That's the only reason I can see that the
connection would need to be torn down.

**Comment by csosto-pk** [comment]
Added text to address it. 

> EST requires the client to use its implicit trust anchor to authenticate the server in the first DTLS connection. After receiving the new trust anchor from the server (cacerts), the client MUST use its newly received explicit trust anchor onwards. While in a persistent DTLS connection, the client SHOULD immediately start using the new trust anchor after receiving the cacerts response and tear down the DTLS connection if the server certificate cannot be validated with the new trust anchor. Alternatively, a client MAY chose to keep the already authenticated by the implicit trust anchor connection open by assuming the the identity of the server is to be trusted even in the first authentication. The explicit trust anchor SHOULD be used starting from the next DTLS connection.

**Comment by csosto-pk** [comment]
Changed it slightly. Added 
> For example, an EST cacerts request that is followed by a simpleenroll request can use the same authenticated DTLS connection. However, some additional rules do apply regarding the use of the Implicit and Explicit TA database (Section 11.1) 

And in the Security considerations section 
> In cases where the IDevID used to authenticate the client is expired the server MAY still authenticate the client because IDevIDs are expected to live as long as the device itself. In such occasions, checking the certificate revocation status or authorizing the client using another method is important for the server to ensure that the client is to be trusted.
