### ISSUE TITLE
unauthenticated /crt and /att

### ISSUE THREAD

**Issue by petervanderstok** [SanKumar2015/EST-coaps#91]
I'm thinking about a Registrar that might be serving both provisional
connections and ones that are just renewing LDevIDs, and maybe ones that
also serve selected factory installed IDevIDs (a use case which est-coaps
caters directly to).

Currently we say that clients need to be authenticated in a DTLS connection
before an EST-coaps request. Do you want to make it more explicit to say
that even though EST allowed for it, EST-coaps does not allow
unauthenticated /crt and /att? We can certainly add that.

I'd like to add this.

**Comment by mcr** [comment]
Does this go into section 5.1? Or a new security considerations?
