### ISSUE TITLE
Section 5.7 CBOR array (Jim's draft-ietf-ace-coap-est-07 WGLC review 1/17/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#97]
Validate that CBOR array is the correct response type not multipart/cbor

**Comment by petervanderstok** [comment]
Actually, the ct is application/multipart-core, which in this particular case is composed of a CBOR array with two items. I suggest:
OLD:
The sever-side key generation response is returned using a CBOR array
   Section 5.2.1.  
NEW
The sever-side key generation response is returned with content format application/multipart-core containing a CBOR array with two elements (see Section 5.2.1).

**Comment by csosto-pk** [comment]
Fixed in commit 6cbbe58. Updated text in section 5.7 to say 
> The sever-side key generation response is returned with content format application/multipart-core [I-D.ietf-core-multipart-ct] containing a CBOR array (Section 5.2.1).

**Comment by csosto-pk** [comment]
> The word item here is going to cause a problem. There are 4 elements in the array, but 2 sub-content types. Which the word items refers to is unclear.

Good point Jim. In reality Peter fixed the sentence a bit already so it now reads 

> The sever-side key generation response is returned with content format application/multipart-core [I-D.ietf-core-multipart-ct] containing a CBOR array with four items (Section 5.2.1).

I think that looks OK now.
