### ISSUE TITLE
Section 6 ArbitraryLabel (Jim's draft-ietf-ace-coap-est-07 WGLC review 1/17/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#98]
Based on earlier mails on the list I expected to see a short description of the purpose of "ArbitraryLabel".  

The fact that there are multiple ways to get the things and they might not be in the same location.  Some guidance for an application on how to decide which method should be used and the choice of an ArbitraryLabel to use would be very helpful.  At present I would guess that I would send a request to the well known address, if that does not work then do a discovery but it might be easier to just do the discovery to begin with and not worry about the well-known address.  That is one would only do discovery if onewas hitting up a resource directory and not the actual machine.  On the other hand if things are rooted at /est rather than in well-known it would lead to shorter requests which once one starts doing block wise would be good.

**Comment by csosto-pk** [comment]
Added sentence the states 
> Arbitrary Labels are usually defined and used by EST CAs in order to route client requests to the appropriate certificate profile.

Also provided more guidance on when to do discovery 
> Discovery SHOULD NOT be chosen when the client is preconfigured to use the default /.well known/est server root resource and port 5684. If the default root resource requests fail, the client SHOULD fall back to doing a resource discovery. Resource discovery SHOULD be employed when non-default URIs (like /est or /est/ArbitraryLabel) or ports are supported by the server or when the client is unaware of what EST-coaps resources are available by the server.

**Comment by csosto-pk** [comment]
Waiting to get confirmation that commit# 3eec580 addresses the concern.

**Comment by petervanderstok** [comment]
s/Discovery SHOULD NOT be chosen /Discovery SHOULD be ignored/

**Comment by csosto-pk** [comment]
Fixed in commit f57499c

Added sentence the states 
> Arbitrary Labels are usually defined and used by EST CAs in order to route client requests to the appropriate certificate profile.

Also provided more guidance on when to do discovery 
> Discovery SHOULD be ignored when the client is preconfigured to use the default /.well known/est server root resource and port 5684. If the default root resource requests fail, the client SHOULD fall back to doing a resource discovery. Resource discovery SHOULD be employed when non-default URIs (like /est or /est/ArbitraryLabel) or ports are supported by the server or when the client is unaware of what EST-coaps resources are available by the server.
